dist: xenial
sudo: false
language: python
cache: pip
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "pypy3.5-6.0"
env:
  - DJANGO="1.11"
  - DJANGO="2.0"
  - DJANGO="2.1"
matrix:
  include:
    - python: 2.7
      env: DJANGO="1.11"
branches:
  only:
    - master
install:
  - ./.travis_setup
script:
  - tox -- --cov
after_success:
  coveralls
