dist: xenial
language: python
cache: pip

matrix:
  fast_finish: true
  include:
    - python: 3.7
      env: TOXENV=black
    - python: 3.7
      env: TOXENV=flake8
    - python: 3.7
      env: TOXENV=isort
    - python: 3.5
      env: TOXENV=py35-dj111
    - python: 3.6
      env: TOXENV=py36-dj111
    - python: 3.7
      env: TOXENV=py37-dj111
    - python: 3.5
      env: TOXENV=py35-dj21
    - python: 3.6
      env: TOXENV=py36-dj21
    - python: 3.7
      env: TOXENV=py37-dj21
    - python: 3.5
      env: TOXENV=py35-dj22
    - python: 3.6
      env: TOXENV=py36-dj22
    - python: 3.7
      env: TOXENV=py37-dj22
    - python: 3.6
      env: TOXENV=py36-dj30
    - python: 3.7
      env: TOXENV=py37-dj30
    - python: 3.6
      env: TOXENV=py36-djmaster
    - python: 3.7
      env: TOXENV=py37-djmaster
  allow_failures:
    - env: TOXENV=py36-djmaster
    - env: TOXENV=py37-djmaster

install:
  - pip install tox

script:
  - tox

after_success:
  - pip install coveralls
  - coveralls
