language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
  - "pypy3"
install:
  - pip install coveralls $DJANGO
  - python setup.py develop
env:
  - DJANGO="django>=1.5,<1.6"
  - DJANGO="django>=1.6,<1.7"
  - DJANGO="django>=1.7,<1.8"
  - DJANGO="django>=1.8,<1.9"
matrix:
  exclude:
    - python: "3.5"
      env: DJANGO="django>=1.5,<1.6"
    - python: "3.5"
      env: DJANGO="django>=1.6,<1.7"
    - python: "3.5"
      env: DJANGO="django>=1.7,<1.8"
script:
  - cd ./testproject; coverage run --source=phonenumber_field manage.py test phonenumber_field testapp
after_success:
  coveralls
